### ISSUE TITLE
Cadastro de Funcionario

### ISSUE THREAD

**Issue by erikborella** [NullTeam-AcademiaDoProgramdor/LocadoraDeVeiculos#1]
- [x] Domínio
- [x] Controlador
- [x] Tela
- [x] Testes unitários
- [x] Testes de integração

| Cadastro de Funcionários|
| ------------------------------ | 
| Como: Admin |
| Eu quero:  Poder cadastrar um funcionário |
| Para então eu poder: Cadastrar veículos e clientes |
| Critérios de aceitação: |
| Deve ter o nome, data de entrada na empresa, salário Deve registrar login e senha |

**Comment by PedroDircksen** [comment]
- [ ] Domínio
- [ ] Controlador
- [ ] Formulário
- [ ] Testes
